### PR TITLE
updated model metadata schema

### PR DESCRIPTION
**Pull request by nickreich**
This is a draft model metadata schema file. Are there additional fields or instructions we want to include? 

This version passes schema/config validation:
```
> validate_hub_config()
...
── $model-metadata-schema 
[1] TRUE
✔ ok:  hub-config/model-metadata-schema.json (from default json schema )
```

Note that this, along with #60 is related to #34

### CODE REVIEW

**Comment by nickreich** [comment]
@dylanhmorris and @kaitejohnson would be curious for your feedback on this as well.

**Comment by kaitejohnson** [comment]
My additional suggestions would be for optional but encouraged fields for:
- link to github repository 
- link to long form model description (e.g. pre-print or markdown file)
-  description of data sources (e.g. NextStrain  + GISAID for sequences outside of the U.S. + wastewater variant proportions)

**Comment by elray1** [comment]
couple of thoughts r.e. Kaitlyn's suggestions (all of which I like):

- could have a more general concept of "code archive", that is, allowing for services other than github.  It might be possible to borrow [this specification](https://github.com/hubverse-org/schemas/blob/2148965efadac7c8199cc670ec84db711fd58f1f/v3.0.1/admin-schema.json#L37-L58) for that.
- just throwing out the idea: would it be too much to actually make the link to a formal model writeup that Kaitlyn suggested a required field?  the downside is that teams may be under a crunch at the start of the season, and this would mean that they couldn't actually submit predictions without having set up a place with their writing.

**Comment by nickreich** [comment]
To address the comments about methods write-ups, in the latest revision I:
- made the `methods` field be a longer (1000 characters) abstract of the methods. (required)
- removed the `methods_long` field (was unlimited)
- added a `methods_url` field (required)

It felt weird to require a brief summary, a longer summary, and then a write-up. So I went for a less-brief summary and then a full write-up, both required.

I also am adding a `data_sources` field.

**Comment by elray1** [comment]
@nickreich are the changes you described just above committed/pushed?

**Comment by nickreich** [comment]
almost

**Comment by nickreich** [comment]
they are now.

**Review by elray1 — APPROVED** [review]
lgtm

**Pull request merged**
