### PR TITLE
Update Model Summary Output

### PR DESCRIPTION
**Pull request by trobacker**
#174 Added roxygen documentation, and now list clades modeled/predicted.

### CODE REVIEW

**Review by nickreich — CHANGES_REQUESTED** [review]
Thanks for this update! All the clades are required to be modeled by every team, so my suggestion would be to make it so that:

1. the list of clade names appears just once, below the "Summary of submissions..." top line. this is required to be the same for all teams, so no need to repeat it.
2. sort the list alphabetically (if you wanted to be fanatical about it, put "other" at the end)
3. add a newline to separate these top two lines from the first model summary.

**Comment by IsaacMacarthur** [comment]
Hi, Nick. I just tried to make the changes you requested. Let me know if this is more like what you pictured.

**Review by trobacker — COMMENTED** [review]
Looks good on my end.

**Review by nickreich — APPROVED** [review]
Yes! looks great. thanks.

**Pull request merged**
