### PR TITLE
DO NOT MERGE: testing model submission

### PR DESCRIPTION
**Pull request by IsaacMacarthur**
Trying issue #79 for the second time.

### CODE REVIEW

**Comment by nickreich** [comment]
@annakrystalli could you take a look at this validation error? It doesn't make sense to me and I wonder if there is a hubValidations bug somewhere with the data types. The output_type_id column for this file is character and it should be, but the validation says:
```
✖ [col_types]: Column data types do not match hub schema.  `output_type_id`
  should be "Date" not "character".
```
But the schema very clearly [says that output_type_id should be character](https://github.com/reichlab/variant-nowcast-hub/blob/727e7f3db1d88ca481d1df7f4c1827aa24fa5e48/hub-config/tasks.json#L265).

**Comment by nickreich** [comment]
I did a bit more exploration by downloading the submission file, renaming it to be a UMass-HMLR file and running the validations locally. The output is encouraging except for the column data types error that happened in the live validation.

```
> validate_model_file(hub_path = ".", file_path = "UMass-HMLR/2024-10-02-UMass-HMLR.parquet")

── 2024-10-02-UMass-HMLR.parquet ────

✔ [file_exists]: File exists at path model-output/UMass-HMLR/2024-10-02-UMass-HMLR.parquet.
✔ [file_name]: File name "2024-10-02-UMass-HMLR.parquet" is valid.
✔ [file_location]: File directory name matches `model_id` metadata in file name.
✔ [round_id_valid]: `round_id` is valid.
✔ [file_format]: File is accepted hub format.
✔ [metadata_exists]: Metadata file exists at path model-metadata/UMass-HMLR.yml.

> validate_model_data(hub_path = ".", file_path = "UMass-HMLR/2024-10-02-UMass-HMLR.parquet")

── 2024-10-02-UMass-HMLR.parquet ────

✔ [file_read]: File could be read successfully.
✔ [valid_round_id_col]: `round_id_col` name is valid.
✔ [unique_round_id]: `round_id` column "nowcast_date" contains a single, unique round ID value.
✔ [match_round_id]: All `round_id_col` "nowcast_date" values match submission `round_id` from
  file name.
✔ [colnames]: Column names are consistent with expected round task IDs and std column names.
✖ [col_types]: Column data types do not match hub schema.  `output_type_id` should be "Date"
  not "character".
✔ [valid_vals]: `tbl` contains valid values/value combinations.
✔ [rows_unique]: All combinations of task ID column/`output_type`/`output_type_id` values are
  unique.
✔ [req_vals]: Required task ID/output type/output type ID combinations all present.
✔ [value_col_valid]: Values in column `value` all valid with respect to modeling task config.
ℹ [value_col_non_desc]: No quantile or cdf output types to check for non-descending values.
  Check skipped.
ℹ [value_col_sum1]: No pmf output types to check for sum of 1. Check skipped.
✔ [spl_compound_taskid_set]: All samples in a model task conform to single, unique compound
  task ID set that matches or is coarser than the configured `compound_taksid_set`.
✔ [spl_compound_tid]: Each sample compound task ID contains single, unique value.
✔ [spl_non_compound_tid]: Task ID combinations of non compound task id values consistent across
  modeling task samples.
✔ [spl_n]: Required samples per compound idx task present.
```

**Comment by annakrystalli** [comment]
A bug indeed! Fixed and ready for review in https://github.com/hubverse-org/hubData/pull/58

Note that you can fully check a submission locally with `hubValidations::validate_submission()`
- https://hubverse-org.github.io/hubValidations/articles/validate-submission.html
- https://hubverse-org.github.io/hubValidations/reference/validate_submission.html

**Comment by nickreich** [comment]
I'm going to say this closes #79.

**Pull request closed without merging**
